# -*- coding: utf-8 -*-
"""01_clean_features.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wqpbBfGgM9nIhzB6jS_O5pmoRs949J8A
"""

# 01_clean_features.py
# GreenVi$or: load Kiva snapshot (zip), filtered funded vs expired, saved cleaned dataset

import os
import zipfile
import pandas as pd

# 1) Path to my zip inside Google Drive
ZIP_PATH = "/content/drive/MyDrive/archive2.zip"

# 2) Where to extract inside Colab runtime (temporary folder)
EXTRACT_DIR = "/content/kiva_snapshot"

# 3) Output cleaned file
OUT_CSV = "/content/kiva_processed.csv"

# Step A: unzip snapshot
os.makedirs(EXTRACT_DIR, exist_ok=True)

if not os.path.exists(os.path.join(EXTRACT_DIR, "loans.csv")):
    with zipfile.ZipFile(ZIP_PATH, "r") as z:
        z.extractall(EXTRACT_DIR)

# Step B: load loans.csv
loans_path = os.path.join(EXTRACT_DIR, "loans.csv")
loans = pd.read_csv(loans_path)

# Step C: filter to binary classes and create target label
df = loans[loans["status"].isin(["funded", "expired"])].copy()
df["y_funded"] = (df["status"] == "funded").astype(int)

# Step D: build one text column (translated first, fallback to raw)
df["text"] = (
    df["description_translated"]
      .fillna(df["description"])
      .fillna("")
      .astype(str)
)

# keep only loans with some text
df = df[df["text"].str.len() > 20].copy()

# Step E: keep only the columns we need downstream
feature_cols = [
    "loan_amount",
    "lender_term",
    "sector_name",
    "activity_name",
    "country_name",
    "repayment_interval",
    "borrower_pictured",
    "borrower_genders",
    "partner_id",
]

keep_cols = ["status", "y_funded", "text"] + feature_cols
keep_cols = [c for c in keep_cols if c in df.columns]  # safety in case some columns are missing

df_out = df[keep_cols].copy()

# Step F: save cleaned dataset
df_out.to_csv(OUT_CSV, index=False)

# Step G: print a tiny log (use this in Table 3.1 + Results 4.1)
print("Saved:", OUT_CSV)
print("Rows:", df_out.shape[0], "Cols:", df_out.shape[1])
print("Class counts:", df_out["y_funded"].value_counts().to_dict())