# -*- coding: utf-8 -*-
"""05_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hpHFEloqTe9t59S1YB6kDKnwHKwu2Y2m
"""

# 05  DECISION RULES (Fund / Review / Reject)



import pandas as pd
import numpy as np
import os


# STEP 0  Load processed dataset (already cleaned)

DATA_PATH = "/content/kiva_processed.csv"
df = pd.read_csv(DATA_PATH, engine="python", on_bad_lines="skip")

print("Rows loaded:", len(df))
print(df.head())


# STEP 1  Create a simple viability signal (proxy)
# Smaller loan amount is treated as "more viable" in this prototype.
# This is a transparent proxy used only for a decision support demo.
max_amt = df["loan_amount"].max()
df["viability_signal"] = 1 - (df["loan_amount"] / max_amt)


# STEP 2  Choose a transparent viability threshold

# Using the median creates a simple 50/50 screening gate.
threshold = df["viability_signal"].median()


# STEP 3  Risk-only screening output (binary)

df["risk_only"] = (df["viability_signal"] >= threshold).astype(int)


# STEP 4  Build a simple impact proxy (transparent)

# Impact proxy is a weighted score from simple observable fields.
# This is not "true impact"  it is a prototype proxy.
df["is_female"] = df["borrower_genders"].astype(str).str.contains("female", case=False).astype(int)
df["has_picture"] = df["borrower_pictured"].astype(str).str.lower().isin(["true", "1", "yes"]).astype(int)

df["impact_proxy"] = (
    0.4 * df["is_female"] +
    0.3 * df["has_picture"] +
    0.3 * (1 - df["loan_amount"] / max_amt)
)


# STEP 5  Fund / Review / Reject decision rules

# Rule structure:
# 1) If not viable -> REJECT
# 2) If viable + high impact -> FUND
# 3) If viable + medium impact -> REVIEW
# 4) Otherwise -> REJECT (conservative)
HIGH_IMPACT_T = 0.75
MED_IMPACT_T  = 0.55

df["final_decision"] = "REJECT"

df.loc[
    (df["viability_signal"] >= threshold) & (df["impact_proxy"] >= MED_IMPACT_T),
    "final_decision"
] = "REVIEW"

df.loc[
    (df["viability_signal"] >= threshold) & (df["impact_proxy"] >= HIGH_IMPACT_T),
    "final_decision"
] = "FUND"

# Risk+Impact flag for figures (fund shortlist only)
df["risk_plus_impact"] = (df["final_decision"] == "FUND").astype(int)

# STEP 6 — Save decision tables for report / appendix

os.makedirs("results", exist_ok=True)

# Appendix preview: top 60 non-rejected cases (fund + review), ranked by impact
df_non_reject = df[df["final_decision"] != "REJECT"].copy()
df_non_reject = df_non_reject.sort_values("impact_proxy", ascending=False)

df_non_reject.head(60).to_csv("results/table_decision_top60.csv", index=False)

# Summary row for results chapter
summary = pd.DataFrame([{
    "threshold": float(threshold),
    "risk_only_count": int(df["risk_only"].sum()),
    "fund_count": int((df["final_decision"] == "FUND").sum()),
    "review_count": int((df["final_decision"] == "REVIEW").sum()),
    "reject_count": int((df["final_decision"] == "REJECT").sum()),
    "HIGH_IMPACT_T": HIGH_IMPACT_T,
    "MED_IMPACT_T": MED_IMPACT_T
}])
summary.to_csv("results/table_decision_summary.csv", index=False)

print("FINAL DECISION TABLES CREATED.")
print("Use results/table_decision_top60.csv in your appendix.")
print("Use results/table_decision_summary.csv in your results.")


# STEP 7  Single-loan demo helper (for prototype screenshot)

def run_greenvisor(amount, gender="female", pictured=True):
    # Viability proxy (same logic as above)
    v = 1 - (amount / max_amt)

    # Impact proxy (same logic as above)
    is_f = 1 if "female" in str(gender).lower() else 0
    has_pic = 1 if pictured else 0
    imp = (0.4 * is_f + 0.3 * has_pic + 0.3 * (1 - amount / max_amt))

    # Apply the same 3-way policy
    if v < threshold:
        decision = "REJECT"
    elif imp >= HIGH_IMPACT_T:
        decision = "FUND"
    elif imp >= MED_IMPACT_T:
        decision = "REVIEW"
    else:
        decision = "REJECT"

    return v, imp, decision

# STEP 8  Sensitivity & Drift Sanity Checks (governance)


# Small threshold shift test (±5%)
t_low  = threshold * 0.95
t_high = threshold * 1.05

df["risk_lowT"]  = (df["viability_signal"] >= t_low).astype(int)
df["risk_highT"] = (df["viability_signal"] >= t_high).astype(int)

sensitivity_summary = pd.DataFrame([{
    "base_threshold": threshold,
    "low_threshold": t_low,
    "high_threshold": t_high,
    "base_viable": int(df["risk_only"].sum()),
    "lowT_viable": int(df["risk_lowT"].sum()),
    "highT_viable": int(df["risk_highT"].sum())
}])

sensitivity_summary.to_csv("results/table_sensitivity_check.csv", index=False)

print("SENSITIVITY CHECK SAVED.")

# FIGURES  Decision comparison (Riskonly vs Impactaligned)


import pandas as pd
import matplotlib.pyplot as plt
import os


# STEP 1  Load decision summary (full dataset counts)

summary = pd.read_csv("/content/results/table_decision_summary.csv")

# Safety: one-row summary is expected
row = summary.iloc[0]

risk_only_count = int(row["risk_only_count"])
fund_count = int(row["fund_count"])
review_count = int(row["review_count"])
reject_count = int(row["reject_count"])


# STEP 2 — Load top60 appendix preview (for distribution plot)

top60 = pd.read_csv("/content/results/table_decision_top60.csv")


# STEP 3 — Create output folder for figures

os.makedirs("/content/figures", exist_ok=True)


# FIGURE 1 — Portfolio behaviour under the two policies

# Risk-only = all viable loans (passes viability gate)
# Risk+Impact = FUND shortlist only (high impact among viable)
counts = pd.Series({
    "Risk-only (viable set)": risk_only_count,
    "Risk+Impact (FUND shortlist)": fund_count
})

plt.figure()
counts.plot(kind="bar")
plt.title("Risk-only vs Risk+Impact Prioritisation (Portfolio Behaviour)")
plt.ylabel("Number of loans")
plt.tight_layout()
plt.savefig("/content/figures/fig_risk_vs_riskimpact.png", dpi=200)
plt.close()


# FIGURE 2 — Impact proxy distribution of FUNDED shortlist (appendix preview)

# Use top60 preview (not full dataset) to show what the funded set looks like.
funded_preview = top60[top60["final_decision"] == "FUND"]

plt.figure()
funded_preview["impact_proxy"].hist(bins=15)
plt.title("Impact Proxy Distribution (FUND shortlist — preview)")
plt.xlabel("Impact proxy score")
plt.ylabel("Frequency")
plt.tight_layout()
plt.savefig("/content/figures/fig_impact_distribution.png", dpi=200)
plt.close()

print("FIGURES CREATED:")
print(" - /content/figures/fig_risk_vs_riskimpact.png")
print(" - /content/figures/fig_impact_distribution.png")

# ==============================
# GreenVi$or — Demo (fast option)
# ==============================


# df, threshold, HIGH_IMPACT_T, MED_IMPACT_T

def run_greenvisor(amount, gender="female", pictured=True):
    # STEP A  proxy viability signal (same as engine)
    viability = 1 - (amount / df["loan_amount"].max())
    is_viable = int(viability >= threshold)

    # STEP B  impact proxy (same as engine)
    is_female = 1 if "female" in str(gender).lower() else 0
    has_picture = 1 if pictured else 0

    impact = (
        0.4 * is_female +
        0.3 * has_picture +
        0.3 * (1 - amount / df["loan_amount"].max())
    )

    # STEP C  decision logic (matches engine: FUND / REVIEW / REJECT)
    if not is_viable:
        decision = "REJECT"   # fails viability gate
    elif impact >= HIGH_IMPACT_T:
        decision = "FUND"     # viable + high impact
    elif impact >= MED_IMPACT_T:
        decision = "REVIEW"   # viable + medium impact
    else:
        decision = "REJECT"   # viable but low impact (not prioritised)

    # Optional extra view (simple, for explanation)
    viability_view = "Viable" if is_viable else "Not viable"

    return viability, impact, viability_view, decision


# ------------------------------
# DEMO INPUTS (change these)
# ------------------------------
amount = 500
gender = "female"
pictured = True

v, i, v_view, decision = run_greenvisor(amount, gender, pictured)

print("GREENVI$OR — DEMO RUN (Prototype Interface)")
print("------------------------------------------")
print("Input: loan_amount =", amount)
print("Input: borrower_gender =", gender)
print("Input: borrower_pictured =", pictured)
print()
print("Output: viability_signal =", round(v, 3))
print("Output: impact_proxy     =", round(i, 3))
print("View 1 (viability screen):", v_view)
print("View 2 (recommendation):", decision)

